[env]
framework = arduino
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip

monitor_speed = 115200
monitor_filters = esp32_exception_decoder

build_flags =
    -D SERIAL_BAUD=115200
    -D WIFI_SSID=\"AllShallBeWell\"
    -D WIFI_PASS=\"AndAllShallBeWell\"

    -DBOARD_HAS_PSRAM

lib_deps =
    LittleFS
    https://github.com/pschatzmann/arduino-audio-tools.git
    https://github.com/pschatzmann/arduino-libhelix.git
    https://github.com/tzapu/WiFiManager

board_build.filesystem = littlefs

[env:kink-box-debug]
board = kink-box
build_type = debug

build_flags =
    ${env.build_flags}
    -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCONFIG_ESP_CONSOLE_USB_CDC=1    



[env:kink-box-release]
board = kink-box

build_type = release
